SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `hw_user` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'User ID',
  `gid` bigint(20) UNSIGNED NOT NULL COMMENT 'Google ID',
  `fname` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Full Name',
  `gname` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Given Name',
  `xname` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Family Name',
  `head` varchar(4096) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Head Image',
  `email` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'E-Mail',
  `token` varchar(40) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Token'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `hw_user`
  ADD PRIMARY KEY (`id`),
  ADD KEY `gid` (`gid`),
  ADD KEY `email` (`email`);


ALTER TABLE `hw_user`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'User ID';
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
